#!/bin/ksh

# OpenBSD rc.d service file for hdfd.
# Assumes a _hdfd user is created with home directory /var/hdfd.
# All logs and crash traces are written to syslog, with hdfd's built-in
# file logging and log rotation disabled by default.
# Save to /etc/rc.d/hdfd and enable with 'hdfd_flags=' in
# /etc/rc.conf.local.

daemon="/usr/local/bin/hdfd"
daemon_user=_hdfd
defaults="-A /var/hdfd --nofilelogging"

. /etc/rc.d/rc.subr

pexp="${daemon} ${defaults} ${daemon_flags}.*"
rc_bg=YES
rc_reload=NO

rc_start() {
	${rcexec} "${daemon} ${defaults} ${daemon_flags} 2>&1 | \
		logger -p daemon.info -t hdfd"
}

rc_cmd $1
